### ISSUE TITLE
Total grenade text during freeze time is too long

### ISSUE THREAD

**Issue by Simber1** [bonocs/csgo-hud#1]
The text that says "Total" before the total grenade count that shows up during freeze time is slightly too long and the l gets clipped off

https://i.imgur.com/W2WbtoI.jpeg

**Comment by bonocs** [comment]
Hey, this is a known issue (my bad for not posting it in the issues section) but this part is being removed completely in the next update as I've completely redesigned the side bar.

**Comment by Simber1** [comment]
👍, The PR also fixes the Top bar issue where the background doesn't quite reach out to the number and names overflowing. I based my version off of your design with the same font so I ran into all 3 of these issues and figured I should merge the fixes into here too for you so we don't both have to fix them.

**Comment by bonocs** [comment]
> 👍, The PR also fixes the Top bar issue where the background doesn't quite reach out to the number and names overflowing. I based my version off of your design with the same font so I ran into all 3 of these issues and figured I should merge the fixes into here too for you so we don't both have to fix them.

Are you making a Blast inspired HUD too or just using the same font? Either way, thanks for your help.

**Comment by Simber1** [comment]
> Out of interest, are you using the player photos feature? If you don't have a photo which the same username the focused player bar will not appear. If you are not using them please comment out line `34` in `FocusedPlayer.vue`

I'm not, I'm using the original `FocusedPlayer.vue`. I kinda made a mashup between your HUD and the original that this forked from then added my own features like team renaming and health being highlighted when low in FocusedPlayer, also adjusted the intro and outro anims   

Right now mine looks like this
![image](https://user-images.githubusercontent.com/16944153/158208266-e77d0801-8963-4987-85fd-304689b778b4.png)

**Comment by bonocs** [comment]
> I'm not, I'm using the original `FocusedPlayer.vue`. I kinda made a mashup between your HUD and the original that this forked from then added my own features like team renaming and health being highlighted when low in FocusedPlayer, also adjusted the intro and outro anims
> 
How did you edit those? I messed around with the styl files and it broke it completely.
